# Generated by Django 4.2.11 on 2026-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
