# Generated by Django 6.0.2 on 2026-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
