# Generated by Django 6.0.2 on 2026-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('col', '0005_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
